### ISSUE TITLE
Typography component enhancements

### ISSUE THREAD

**Issue by seanrcollings** [atomicjolt/atomic-libs#112]
Add sizing props to typography components 

```tsx
<Text $maxWidth="75ch" > Here is some text </Text>
```

Add a clamping option to typography components 

```tsx
<Text $clamp="2">
  Here is some text 
</Text>
```

Which would output something similar to: 
```css
.two-line-clamp {
  display: -webkit-box;
  line-clamp: 2;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
```
