### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by seanrcollings** [atomicjolt/atomic-libs#87]
```css
.aj-list {
  border: 2px solid var(--border-clr-primary);
  border-radius: var(--radius);

  &__item {
    padding: 1.2rem 1.6rem;

    &:not(:last-child) {
      border-bottom: var(--border);
    }
  }
}
```
